
"""Fuzzy-c-meas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1faw-x7V_XqNfq82EHlDRxXzzWG1VbKbg
"""

import kagglehub
path = kagglehub.dataset_download("msjahid/bangladesh-districts-wise-population")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import kagglehub


path = kagglehub.dataset_download("msjahid/bangladesh-districts-wise-population")
csv_path = os.path.join(path, 'city_population.csv') # Based on dataset structure
df = pd.read_csv(csv_path)


features = ['Population_2022', 'Area (km2)']
X = df[features].values


X_min = X.min(axis=0)
X_max = X.max(axis=0)
X_scaled = (X - X_min) / (X_max - X_min)


def fuzzy_c_means(X, n_clusters, m=2, max_iter=100, tol=1e-5):
    
    n_samples = X.shape[0]
    U = np.random.dirichlet(np.ones(n_clusters), size=n_samples)

    for _ in range(max_iter):
        U_old = U.copy()

        
        um = U**m
        centroids = (um.T @ X) / um.sum(axis=0)[:, None]

        
        distances = np.linalg.norm(X[:, None] - centroids, axis=2)

        
        distances = np.fmax(distances, 1e-10)
        inv_dist = 1.0 / distances
        U = (inv_dist**(2/(m-1))) / (inv_dist**(2/(m-1))).sum(axis=1)[:, None]

        
        if np.linalg.norm(U - U_old) < tol:
            break

    return centroids, U


n_clusters = 3
centroids, U = fuzzy_c_means(X_scaled, n_clusters=n_clusters)


df['Cluster'] = np.argmax(U, axis=1)

df['Fuzzy_Score'] = np.max(U, axis=1)


plt.figure(figsize=(10, 6))
scatter = plt.scatter(X[:, 0], X[:, 1], c=df['Cluster'], cmap='viridis', s=df['Fuzzy_Score']*100, alpha=0.7)
plt.colorbar(scatter, label='Cluster ID')


centroids_orig = centroids * (X_max - X_min) + X_min
plt.scatter(centroids_orig[:, 0], centroids_orig[:, 1], marker='X', s=200, c='red', label='Centroids')

plt.title('Fuzzy C-Means Clustering of Bangladesh Districts')
plt.xlabel('Population (2022)')
plt.ylabel('Area (km²)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()


print("Top 5 Districts with their Cluster and Fuzzy Membership Score:")
print(df[['Name', 'Population_2022', 'Cluster', 'Fuzzy_Score']].head())
