# -*- coding: utf-8 -*-
"""Fuzzy-c-meas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1faw-x7V_XqNfq82EHlDRxXzzWG1VbKbg
"""

import kagglehub
path = kagglehub.dataset_download("msjahid/bangladesh-districts-wise-population")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import kagglehub

# 1. Download and Load Data
path = kagglehub.dataset_download("msjahid/bangladesh-districts-wise-population")
csv_path = os.path.join(path, 'city_population.csv') # Based on dataset structure
df = pd.read_csv(csv_path)

# 2. Preprocessing
# We cluster based on 'Population_2022' and 'Area (km2)'
# Note: Ensure column names match your CSV (they are usually case-sensitive)
features = ['Population_2022', 'Area (km2)']
X = df[features].values

# Normalize data (FCM is sensitive to scale)
X_min = X.min(axis=0)
X_max = X.max(axis=0)
X_scaled = (X - X_min) / (X_max - X_min)

# 3. Fuzzy C-Means Implementation
def fuzzy_c_means(X, n_clusters, m=2, max_iter=100, tol=1e-5):
    # Initialize membership matrix randomly
    n_samples = X.shape[0]
    U = np.random.dirichlet(np.ones(n_clusters), size=n_samples)

    for _ in range(max_iter):
        U_old = U.copy()

        # Calculate centroids
        um = U**m
        centroids = (um.T @ X) / um.sum(axis=0)[:, None]

        # Calculate distances
        distances = np.linalg.norm(X[:, None] - centroids, axis=2)

        # Update membership matrix
        # Avoid division by zero
        distances = np.fmax(distances, 1e-10)
        inv_dist = 1.0 / distances
        U = (inv_dist**(2/(m-1))) / (inv_dist**(2/(m-1))).sum(axis=1)[:, None]

        # Check for convergence
        if np.linalg.norm(U - U_old) < tol:
            break

    return centroids, U

# Run the algorithm
n_clusters = 3
centroids, U = fuzzy_c_means(X_scaled, n_clusters=n_clusters)

# Get the "hard" cluster assignment (highest membership)
df['Cluster'] = np.argmax(U, axis=1)
# Store the "fuzziness" (maximum membership score)
df['Fuzzy_Score'] = np.max(U, axis=1)

# 4. Visualization
plt.figure(figsize=(10, 6))
scatter = plt.scatter(X[:, 0], X[:, 1], c=df['Cluster'], cmap='viridis', s=df['Fuzzy_Score']*100, alpha=0.7)
plt.colorbar(scatter, label='Cluster ID')

# Convert centroids back to original scale for plotting
centroids_orig = centroids * (X_max - X_min) + X_min
plt.scatter(centroids_orig[:, 0], centroids_orig[:, 1], marker='X', s=200, c='red', label='Centroids')

plt.title('Fuzzy C-Means Clustering of Bangladesh Districts')
plt.xlabel('Population (2022)')
plt.ylabel('Area (km²)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

# Display results
print("Top 5 Districts with their Cluster and Fuzzy Membership Score:")
print(df[['Name', 'Population_2022', 'Cluster', 'Fuzzy_Score']].head())