# -*- coding: utf-8 -*-
"""GRNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cMmAiTh1LdkYlFZOEi0YvdZ_6XRWnfno
"""

import kagglehub
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
!pip install pyGRNN
# You may need to install this: pip install pyGRNN
from pyGRNN import GRNN

# 1. Download and Load Dataset
path = kagglehub.dataset_download("muratkokludataset/pumpkin-seeds-dataset")
df = pd.read_excel(f"{path}/Pumpkin_Seeds_Dataset/Pumpkin_Seeds_Dataset.xlsx")

# 2. Preprocessing
X = df.drop('Class', axis=1).values
y = df['Class'].values

# Encode labels ('Çerçevelik' -> 0, 'Ürgüp Sivrisi' -> 1)
le = LabelEncoder()
y = le.fit_transform(y)

# Split and Scale (Crucial for GRNN as it uses Euclidean distance)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 3. Initialize and "Train" GRNN
# The 'sigma' (spread) is the most important hyperparameter
# If sigma is too small, it overfits; if too large, it blurs the classes
grnn = GRNN(calibration="gradient_search")
grnn.fit(X_train, y_train)

# 4. Predict and Evaluate
# GRNN outputs continuous values, so we round to the nearest class (0 or 1)
y_pred_continuous = grnn.predict(X_test)
y_pred = np.round(y_pred_continuous).astype(int)

# 5. Results
print(f"GRNN Accuracy: {accuracy_score(y_test, y_pred):.2%}")
print("\nDetailed Report:\n", classification_report(y_test, y_pred, target_names=le.classes_))