# -*- coding: utf-8 -*-
"""HDBSCAN and DBSCAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trhCyPw7HecSXfB-Ats2ekw1bHRYuOtE
"""

import pandas as pd
import numpy as np
import os
import kagglehub
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import DBSCAN, HDBSCAN
from sklearn.preprocessing import StandardScaler

# 1. Download and Load Data
path = kagglehub.dataset_download("msjahid/bangladesh-districts-wise-population")
csv_path = os.path.join(path, 'city_population.csv')
df = pd.read_csv(csv_path)

# 2. Preprocessing
# We cluster based on Population and Area
# Using 2022 population and Area columns
X = df[['Population_2022', 'Area (km2)']]

# Density-based algorithms are EXTREMELY sensitive to scale.
# We must scale the data so that 1km2 is comparable to 1 person in distance math.
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 3. Apply DBSCAN (Density-Based Spatial Clustering of Applications with Noise)
# eps: The maximum distance between two samples for them to be considered neighbors.
# min_samples: The number of samples in a neighborhood for a point to be a core point.
dbscan = DBSCAN(eps=0.5, min_samples=3)
df['DBSCAN_Cluster'] = dbscan.fit_predict(X_scaled)

# 4. Apply HDBSCAN (Hierarchical DBSCAN)
# Unlike DBSCAN, HDBSCAN finds clusters of varying densities and doesn't need 'eps'.
hdbscan = HDBSCAN(min_cluster_size=3, min_samples=2)
df['HDBSCAN_Cluster'] = hdbscan.fit_predict(X_scaled)

# 5. Visualization
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# DBSCAN Plot
sns.scatterplot(data=df, x='Population_2022', y='Area (km2)',
                hue='DBSCAN_Cluster', palette='viridis', ax=ax1, s=100)
ax1.set_title('DBSCAN Clustering\n(Fixed Density)')

# HDBSCAN Plot
sns.scatterplot(data=df, x='Population_2022', y='Area (km2)',
                hue='HDBSCAN_Cluster', palette='magma', ax=ax2, s=100)
ax2.set_title('HDBSCAN Clustering\n(Variable Density)')

plt.tight_layout()
plt.show()

# Identifying Outliers
outliers = df[df['HDBSCAN_Cluster'] == -1]
print(f"Detected {len(outliers)} outliers (noise points) using HDBSCAN:")
print(outliers[['Name', 'Population_2022', 'Area (km2)']].head())