# -*- coding: utf-8 -*-
"""Hierarchical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XeHfGRF_aHE6j-N2SkgbEdEtpeu0b9Ca
"""

import kagglehub
path = kagglehub.dataset_download("jessicali9530/animal-crossing-new-horizons-nookplaza-dataset")

import pandas as pd
import os
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster

# 1. Load the Villagers data
csv_path = os.path.join(path, 'villagers.csv')
df = pd.read_csv(csv_path)

# 2. Prepare features (Gender, Species, Personality)
features = ['Gender', 'Species', 'Personality']
X = df[features].copy()

# Encode strings to numbers so the math works
le = LabelEncoder()
for col in features:
    X[col] = le.fit_transform(X[col])

# 3. Perform Hierarchical Clustering
# 'ward' method minimizes the variance within clusters
linked = linkage(X, method='ward')

# 4. Plot the Dendrogram
plt.figure(figsize=(12, 7))
dendrogram(linked,
           orientation='top',
           labels=df['Name'].values,
           distance_sort='descending',
           show_leaf_counts=True)

plt.title('Hierarchical Clustering Dendrogram (Villagers)')
plt.xlabel('Villager Name')
plt.ylabel('Euclidean Distance')
plt.xticks(rotation=90)
plt.show()

# 5. Assign Clusters
# Let's cut the tree to create 6 clusters
df['Hierarchical_Cluster'] = fcluster(linked, 6, criterion='maxclust')

print("Villagers grouped by Hierarchical Clustering:")
print(df[['Name', 'Species', 'Personality', 'Hierarchical_Cluster']].head(15))