# -*- coding: utf-8 -*-
"""LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/172ibOBYppnG9pPD3V1czCfHvX--m0VdW
"""

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from torch.utils.data import DataLoader, TensorDataset
import kagglehub

# 1. DATA PREPARATION
path = kagglehub.dataset_download("muratkokludataset/date-fruit-datasets")
df = pd.read_excel(path)
X = df.drop('Class', axis=1).values
y = LabelEncoder().fit_transform(df['Class'])

# Scale data (Transformers are sensitive to scale)
scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convert to PyTorch Tensors
X_train_t = torch.FloatTensor(X_train).unsqueeze(-1) # Add 'token' dimension
y_train_t = torch.LongTensor(y_train)
X_test_t = torch.FloatTensor(X_test).unsqueeze(-1)
y_test_t = torch.LongTensor(y_test)

train_loader = DataLoader(TensorDataset(X_train_t, y_train_t), batch_size=32, shuffle=True)

# 2. THE LLM ALGORITHM (Transformer Encoder)
class DateTransformer(nn.Module):
    def __init__(self, num_features, num_classes):
        super().__init__()
        self.embed = nn.Linear(1, 64) # Continuous Value Embedding
        self.pos_embed = nn.Parameter(torch.zeros(1, num_features, 64))

        # The core LLM Algorithm: Multi-Head Attention
        encoder_layer = nn.TransformerEncoderLayer(d_model=64, nhead=4, dim_feedforward=128, batch_first=True)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=3)

        self.classifier = nn.Linear(64 * num_features, num_classes)

    def forward(self, x):
        x = self.embed(x) + self.pos_embed
        x = self.transformer(x)
        x = x.view(x.size(0), -1) # Flatten for classification
        return self.classifier(x)

# 3. TRAINING
model = DateTransformer(X.shape[1], len(np.unique(y)))
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

for epoch in range(50):
    for batch_x, batch_y in train_loader:
        optimizer.zero_grad()
        loss = criterion(model(batch_x), batch_y)
        loss.backward()
        optimizer.step()

# 4. EVALUATION
model.eval()
with torch.no_grad():
    outputs = model(X_test_t)
    _, predicted = torch.max(outputs, 1)
    accuracy = (predicted == y_test_t).sum().item() / len(y_test_t)

print(f"Algorithm: Transformer (LLM-based)\nAccuracy: {accuracy * 100:.2f}%")