# -*- coding: utf-8 -*-
"""MLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18PG8ZRiSueVau1730HGPYtzNO-qwNput
"""

import kagglehub
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, accuracy_score

# 1. Download and Load Dataset
path = kagglehub.dataset_download("yashdevladdha/uber-ride-analytics-dashboard")
# The main file in this dataset is 'ncr_ride_bookings.csv'
df = pd.read_csv(f"{path}/ncr_ride_bookings.csv")

# 2. Basic Preprocessing
# Drop columns that are unique IDs or contain mostly NaNs (reasons for cancellation)
cols_to_drop = ['Booking ID', 'Customer ID', 'Date', 'Time', 'Pickup Location', 'Drop Location',
                'Reason for cancelling by Customer', 'Driver Cancellation Reason', 'Incomplete Rides Reason']
df = df.drop(columns=cols_to_drop)

# Handle Missing Values (using median for numerical columns)
# Iterate through all numerical columns and impute NaNs
for col in df.select_dtypes(include=np.number).columns:
    # Exclude the target column if it's already numerical and has no NaNs (or will be handled by LabelEncoder later)
    if col != 'Booking Status' and df[col].isnull().any():
        df[col] = df[col].fillna(df[col].median())

# 3. Encode Categorical Data
le = LabelEncoder()
categorical_cols = ['Vehicle Type', 'Payment Method']
for col in categorical_cols:
    df[col] = le.fit_transform(df[col].astype(str))

# Encode the Target (Booking Status)
df['Booking Status'] = le.fit_transform(df['Booking Status'])

# 4. Prepare Features (X) and Target (y)
X = df.drop('Booking Status', axis=1)
y = df['Booking Status']

# Split Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 5. Feature Scaling (Essential for MLPs)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 6. Initialize and Train MLP
# We use two hidden layers with 64 and 32 neurons respectively
mlp = MLPClassifier(hidden_layer_sizes=(64, 32),
                    activation='relu',
                    solver='adam',
                    max_iter=300,
                    random_state=42)

mlp.fit(X_train, y_train)

# 7. Evaluate
predictions = mlp.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, predictions):.2%}")
print("\nClassification Report:\n", classification_report(y_test, predictions))