# -*- coding: utf-8 -*-
"""modified k - means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14jE5Ue-ScJEwBuq_3RbtQAniLqj8yLPJ
"""

import kagglehub
path = kagglehub.dataset_download("jessicali9530/animal-crossing-new-horizons-nookplaza-dataset")

import pandas as pd
import os
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt

# 1. Load the Villagers data
# path was defined in your previous step
csv_path = os.path.join(path, 'villagers.csv')
df = pd.read_csv(csv_path)

# 2. Select features to cluster on
# We'll use 'Gender', 'Species', and 'Personality'
features = ['Gender', 'Species', 'Personality']
X = df[features].copy()

# 3. Modification: Label Encoding
# K-Means needs numbers. We convert "Lazy" or "Jock" into 0, 1, 2...
le = LabelEncoder()
for col in features:
    X[col] = le.fit_transform(X[col])

# 4. Run K-Means
# Let's group them into 6 distinct "Neighborhood Archetypes"
kmeans = KMeans(n_clusters=6, init='k-means++', random_state=42)
df['Cluster'] = kmeans.fit_predict(X)

# 5. Visualize the Clusters
plt.figure(figsize=(10, 6))
# Using Personality vs Species for the axes
plt.scatter(X['Personality'], X['Species'], c=df['Cluster'], cmap='rainbow', s=100, alpha=0.6)
plt.title('Animal Crossing Villager Clusters')
plt.xlabel('Personality (Encoded)')
plt.ylabel('Species (Encoded)')
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

# Show the results
print("Sample of Villager Groups:")
print(df[['Name', 'Species', 'Personality', 'Cluster']].head(10))

from google.colab import drive
drive.mount('/content/drive')