# -*- coding: utf-8 -*-
"""RFR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N884e3qLxli1_3NbG8swYQjUn9PfJ7KN
"""

import pandas as pd
import kagglehub
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

# Download and load
path = kagglehub.dataset_download("uciml/iris")
df = pd.read_csv(f"{path}/Iris.csv")

# Preprocessing
X = df.drop(['Id', 'Species'], axis=1)
y = df['Species']

# Encode target labels (Setosa=0, Versicolor=1, Virginica=2)
le = LabelEncoder()
y = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestRegressor

rfr = RandomForestRegressor(n_estimators=100, random_state=42)
rfr.fit(X_train, y_train)
# Round predictions to nearest class integer
y_pred_rfr = rfr.predict(X_test).round()

print(f"RFR Accuracy (Rounded): {accuracy_score(y_test, y_pred_rfr) * 100:.2f}%")