# -*- coding: utf-8 -*-
"""semi-supervised.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qm8kP9DVxm8or3jiy10_siSsB34iZ6Ua
"""

import pandas as pd
import numpy as np
import os
import kagglehub
from sklearn.semi_supervised import LabelSpreading
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# 1. Load Data
path = kagglehub.dataset_download("kimjihoo/coronavirusdataset")
df = pd.read_csv(os.path.join(path, 'PatientInfo.csv'))

# 2. Preprocessing
df['target'] = df['state'].apply(lambda x: 1 if x == 'deceased' else 0)
df['age_clean'] = df['age'].astype(str).str.extract('(\d+)').astype(float)
sub_df = df[['age_clean', 'sex', 'target']].dropna().copy()
sub_df['sex_encoded'] = LabelEncoder().fit_transform(sub_df['sex'].astype(str))

X = sub_df[['age_clean', 'sex_encoded']].values
y = sub_df['target'].values

# 3. Train-Test Split (80% Train, 20% Test)
# We keep the Test set completely separate to evaluate final accuracy
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale based on Training data only (to avoid data leakage)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 4. Hide Labels in the Training Set
# We hide 70% of the labels in the TRAINING set to simulate semi-supervised learning
rng = np.random.RandomState(42)
y_train_masked = np.copy(y_train)
random_unlabeled_points = rng.rand(len(y_train)) < 0.7
y_train_masked[random_unlabeled_points] = -1

# 5. Train the Model
lp_model = LabelSpreading(kernel='knn', n_neighbors=7)
lp_model.fit(X_train_scaled, y_train_masked)

# 6. Predict on the unseen Test Set
# The model uses the "spread" logic to predict entirely new data
y_pred = lp_model.predict(X_test_scaled)

# 7. Final Results
print("--- Performance Evaluation ---")
print(f"Accuracy Score: {accuracy_score(y_test, y_pred) * 100:.2f}%")
print("\nDetailed Classification Report:")
print(classification_report(y_test, y_pred, target_names=['Survived/Other', 'Deceased']))