# -*- coding: utf-8 -*-
"""SOM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12euFiJV3oZambWgTuUbT33taXESjAm9e
"""

!pip install minisom
import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from minisom import MiniSom
from sklearn.preprocessing import MinMaxScaler

# 1. Download and Load Dataset
path = kagglehub.dataset_download("muratkokludataset/pumpkin-seeds-dataset")
# The dataset is typically provided as an Excel or CSV file
df = pd.read_excel(f"{path}/Pumpkin_Seeds_Dataset/Pumpkin_Seeds_Dataset.xlsx")

# 2. Data Preprocessing
# Extract features (first 12 columns) and labels (last column)
data = df.iloc[:, 0:12].values
labels = df.iloc[:, 12].values

# Convert labels to numbers for visualization
# 'Çerçevelik' -> 0, 'Ürgüp Sivrisi' -> 1
label_map = {label: i for i, label in enumerate(np.unique(labels))}
target = np.array([label_map[l] for l in labels])

# Scale the data (SOMs are distance-based and require scaling)
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data)

# 3. Initialize and Train SOM
# Grid size: 15x15 neurons. Input_len: 12 features.
som_grid_x, som_grid_y = 15, 15
som = MiniSom(som_grid_x, som_grid_y, 12, sigma=1.5, learning_rate=0.5)

# Initialize weights and train
som.pca_weights_init(data_scaled)
som.train_random(data_scaled, 1000, verbose=True)

# 4. Visualization: The U-Matrix
plt.figure(figsize=(10, 10))
plt.pcolor(som.distance_map().T, cmap='bone_r') # Distance map (U-Matrix)
plt.colorbar()

# Overlay the winning neurons for each seed type
markers = ['o', 's'] # Circle for Cercevelik, Square for Urgup Sivrisi
colors = ['C0', 'C1'] # Blue and Orange

for i, x in enumerate(data_scaled):
    w = som.winner(x) # Get the winning neuron for this sample
    plt.plot(w[0] + 0.5, w[1] + 0.5, markers[target[i]],
             markerfacecolor='None', markeredgecolor=colors[target[i]],
             markersize=8, markeredgewidth=2)

plt.title('SOM U-Matrix: Pumpkin Seed Varieties')
plt.show()