# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14bqO7mjYP9WF-9uAPhn1tUR6oUj76jqt
"""

import kagglehub
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

# Download and load
path = kagglehub.dataset_download("gregorut/videogamesales")
df = pd.read_csv(f"{path}/vgsales.csv")

# Clean missing values
df = df.dropna(subset=['Year', 'Publisher'])

# Create target variable (Binary Classification: Is it a 'Hit'?)
df['Is_Hit'] = (df['Global_Sales'] > 1.0).astype(int)

# Select features and encode categories
le = LabelEncoder()
df['Platform_Enc'] = le.fit_transform(df['Platform'])
df['Genre_Enc'] = le.fit_transform(df['Genre'])

X = df[['Platform_Enc', 'Genre_Enc', 'Year']]
y = df['Is_Hit']

# Split the data (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaling is CRITICAL for SVM performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize and Train
svm_model = SVC(kernel='rbf', C=1.0, gamma='scale')
svm_model.fit(X_train, y_train)

# Predict
y_pred = svm_model.predict(X_test)

# Results
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2%}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))